version: '3.8'

services:
  food-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-mcp-server
    ports:
      - "${MCP_PORT:-8001}:8001"
    environment:
      - MCP_HOST=${MCP_HOST:-0.0.0.0}
      - MCP_PORT=${MCP_PORT:-8001}
    restart: unless-stopped
    networks:
      - food-mcp-network
    # Optional: Add resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Optional: Add logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  food-mcp-network:
    driver: bridge
